# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/tsundered/main.go
    binary: tsundered
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/tsunderectl/main.go
    binary: tsunderectl
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: '{{ .ProjectName }}_checksum.txt'

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/tukeJonny/tsundere
  description: Simple dynamic firewall
  maintainer: Tukejonny <ne250143@yahoo.co.jp>
  license: MIT
  vendor: Tukejonny
  formats:
  - deb
  - rpm
  dependencies:
  - git
  recommends:
  - rpm
  files:
  - deploy/tsundered.service
